# Reusable release brancher workflow
# See SHIP-0038: https://github.com/shipwright-io/community/pull/194
name: Release Brancher
on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      git-ref:
        required: false
        type: string
jobs:
  release-brancher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.git-ref }}
    - name: Create release branch
      env:
        RELEASE_VERSION: release-${{ inputs.release-version }}
      run: |
        git switch -c "${RELEASE_VERSION}"
        git push --set-upstream origin "${RELEASE_VERSION}"
